version: '3'

services:
  coditor-mongodb:
    image: mongo
    container_name: coditor-mongo
    environment:
      MONGO_INITDB_DATABASE: coditor
    volumes:
      - ./config/data.js:/docker-entrypoint-initdb.d/data.js
    ports:
      - '27017:27017'